
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /validate-claim-tmax-io-v1alpha1-namespaceclaim
  failurePolicy: Fail
  name: vnamespaceclaim.kb.io
  admissionReviewVersions: ["v1beta1", "v1"]
  rules:
  - apiGroups:
    - claim.tmax.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - namespaceclaims
    - namespaceclaims/status
  sideEffects: NoneOnDryRun
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /validate-claim-tmax-io-v1alpha1-resourcequotaclaim
  failurePolicy: Fail
  name: vresourcequotaclaim.kb.io
  admissionReviewVersions: ["v1beta1", "v1"]
  rules:
  - apiGroups:
    - claim.tmax.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - resourcequotaclaims
    - resourcequotaclaims/status
  sideEffects: NoneOnDryRun
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /validate-claim-tmax-io-v1alpha1-rolebindingclaim
  failurePolicy: Fail
  name: vrolebindingclaim.kb.io
  admissionReviewVersions: ["v1beta1", "v1"]
  rules:
  - apiGroups:
    - claim.tmax.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - rolebindingclaims/status
  sideEffects: NoneOnDryRun
