## Append samples you want in your CSV to this file as resources ##
resources:
- claim_v1alpha1_namespaceclaim.yaml
- claim_v1alpha1_rolebindingclaim.yaml
- claim_v1alpha1_resourcequotaclaim.yaml
- core_v1_resourcequota.yaml
- rbac.authorization.k8s.io_v1_rolebinding.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
